"""Bursa-format Scope 2 PDF export (3rd Edition style, hackathon-grade)."""
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def build_scope2_pdf(
    building_name: str,
    period_label: str,
    total_kwh: float,
    baseline_kwh: float,
    avoided_kwh: float,
    emission_factor: float,
    scope2_kg: float,
    avoided_kg: float,
    md_savings_rm: float,
    department_rows: list,
) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="EcoTrust Scope 2 Report")
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=colors.HexColor("#10b981"))
    body = styles["BodyText"]

    story = []
    story.append(Paragraph("EcoTrust — GHG Protocol Scope 2 Report", h1))
    story.append(Paragraph(
        f"<b>Building:</b> {building_name} &nbsp;&nbsp; <b>Period:</b> {period_label}", body))
    story.append(Paragraph(
        f"<b>Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body))
    story.append(Spacer(1, 0.6 * cm))

    story.append(Paragraph("Energy Summary", styles["Heading2"]))
    energy_tbl = Table([
        ["Metric", "Value"],
        ["Baseline consumption (kWh)", f"{baseline_kwh:,.1f}"],
        ["Actual consumption (kWh)", f"{total_kwh:,.1f}"],
        ["Avoided consumption (kWh)", f"{avoided_kwh:,.1f}"],
        ["TNB grid emission factor", f"{emission_factor} kgCO2e/kWh"],
        ["Scope 2 emissions", f"{scope2_kg:,.2f} kgCO2e"],
        ["Avoided emissions", f"{avoided_kg:,.2f} kgCO2e"],
        ["Estimated MD bill savings", f"RM {md_savings_rm:,.2f}/mo"],
    ], colWidths=[8 * cm, 7 * cm])
    energy_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]))
    story.append(energy_tbl)
    story.append(Spacer(1, 0.6 * cm))

    story.append(Paragraph("Department Breakdown", styles["Heading2"]))
    dept_data = [["Department", "kWh", "kgCO2e", "Score"]] + department_rows
    dept_tbl = Table(dept_data, colWidths=[6 * cm, 3 * cm, 3 * cm, 3 * cm])
    dept_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]))
    story.append(dept_tbl)
    story.append(Spacer(1, 0.8 * cm))

    story.append(Paragraph(
        "<i>Generated by EcoTrust — Zero-Trust Energy Ecosystem. "
        "Audit-ready evidence per Bursa Malaysia Sustainability Reporting Guide (3rd Edition).</i>",
        body,
    ))

    doc.build(story)
    return buf.getvalue()
